### ISSUE TITLE
Minidocs transform breaks CLI build

### ISSUE THREAD

**Issue by joehand** [freeman-lab/minidocs#51]
I updated to 4.0.0 and changed the transform to the minidocs transform but cannot build the site anymore. 

The `parse-options` module is being called twice and the second time ([from `minidocs/transform`](https://github.com/freeman-lab/minidocs/blob/master/transform.js#L20)) `options.contents` is no longer a path but an array. 

So in parse options [line 9](https://github.com/freeman-lab/minidocs/blob/master/lib/parse-options.js#L8), `var contentsPath = path.resolve(options.dir, options.contents)` fails.

Happy to PR but couldn't quite figure out where/why contents is changing from the path to contents array.

### `parse-options` options:

```js
options = { title: 'The Dat Project',
  logo: 'dat-data.png',
  contents: 
   [ { depth: 1, name: 'Introduction' },
     { depth: 2,
       name: 'Welcome to Dat',
       source: 'http://github.com/datproject/docs',
       contributors: [Object],
       key: 'welcome',
       link: '/welcome' },
    ...
   ],
  markdown: '/Users/joe/node_modules/dat-docs',
  initial: 'welcome',
  basedir: '',
  dir: '/Users/joe/node_modules/dat-docs/dist',
  routes: {}
  ...
```

## Full error

```bash
> minidocs . -c contents.json -i welcome -o dist -l dat-data.png -t 'The Dat Project' -s styles.css --full-html

{ TypeError: Path must be a string. Received [ { depth: 1, name: 'Introduction' },
  { depth: 2,
    name: 'How Dat Works',
    key: 'how-dat-works',
    link: '/how-dat-works' },
  { depth: 1, name: 'Ecosystem' },
  { depth: 2,
    name: 'Overview',
    key: 'ecosystem',
    link: '/ecosystem' },
  { depth: 1, name: 'Specification' },
  { depth: 2,
    name: 'hyperdrive',
    key: 'hyperdrive',
    link: '/hyperdrive' },
  { depth: 2, name: 'meta.dat', key: 'meta.dat', link: '/meta.dat' },
  { depth: 1, name: 'References' },
  { depth: 2, name: 'API', key: 'api', link: '/api' },
  { depth: 2, name: 'DIY Dat', key: 'diy-dat', link: '/diy-dat' } ] while parsing file: /Users/joe/node_modules/dat-docs/dist/index.js
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at module.exports (/Users/joe/node_modules/minidocs/lib/parse-options.js:8:27)
    at staticModule.minidocs (/Users/joe/node_modules/minidocs/transform.js:20:27)
    at walk (/Users/joe/node_modules/minidocs/node_modules/static-eval/index.js:89:27)
    at module.exports (/Users/joe/node_modules/minidocs/node_modules/static-eval/index.js:114:7)
    at traverse (/Users/joe/node_modules/minidocs/node_modules/static-module/index.js:256:23)
    at walk (/Users/joe/node_modules/minidocs/node_modules/static-module/index.js:224:18)
    at walk (/Users/joe/node_modules/minidocs/node_modules/falafel/index.js:49:9)
    at /Users/joe/node_modules/minidocs/node_modules/falafel/index.js:46:17
  filename: '/Users/joe/node_modules/dat-docs/dist/index.js',
  stream: {...}
```

**Comment by joehand** [comment]
Removed the browserify minidocs transform from package.json and it worked.

**Comment by sethvincent** [comment]
Cool! I'll add a note to the readme about this.
