### ISSUE TITLE
Errors with basic example

### ISSUE THREAD

**Issue by mathisonian** [freeman-lab/minidocs#72]
I tried both (1) running the simple example from the readme against versions `4.2` and `4.1` on npm  and (2) cloning and running `examples/cli` locally and got the same error in the browser both times:
```
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '}' is not a valid attribute name.
    at belCreateElement (http://172.28.7.59:9966/bundle.js:1329:14)
    at http://172.28.7.59:9966/bundle.js:6731:12
    at http://172.28.7.59:9966/bundle.js:6782:45
    at module.exports (http://172.28.7.59:9966/bundle.js:160:14)
    at chooWrap (http://172.28.7.59:9966/bundle.js:4365:18)
    at emit (http://172.28.7.59:9966/bundle.js:20855:22)
    at match (http://172.28.7.59:9966/bundle.js:18401:19)
    at onReady (http://172.28.7.59:9966/bundle.js:4307:25)
    at HTMLDocument.onLoad (http://172.28.7.59:9966/bundle.js:4585:5)
```

I'm on node 6.9. This causes the list of pages to not appear in the sidebar:

<img width="1554" alt="screen shot 2017-03-31 at 1 47 38 pm" src="https://cloud.githubusercontent.com/assets/1074773/24568886/a5cfe754-1618-11e7-8cdc-c58c3ca18eb2.png">

**Comment by sethvincent** [comment]
@mathisonian I just fixed a little typo.

A stray `}` was floating around in a bel component somehow 🙃.

v4.2.3 should work as expected.

**Comment by mathisonian** [comment]
woo! thanks!!

just pulled and everything seems 👌
